# Generated by Django 2.2.2 on 2019-07-06 03:57

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_website'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='website',
        ),
        migrations.AddField(
            model_name='post',
            name='url',
            field=models.TextField(default=django.utils.timezone.now, validators=[django.core.validators.URLValidator()]),
            preserve_default=False,
        ),
    ]
