# Generated by Django 2.1 on 2020-01-05 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_remove_post_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='url',
            field=models.URLField(default=1, verbose_name=200),
            preserve_default=False,
        ),
    ]
